project_name: kani

builds:
  - binary: kani
    main: ./cmd/kani/
    env:
      - CGO_ENABLED=0
      - GOGC=off
    ldflags:
      - "-s -w"
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"

archives:
  - id: kani
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: "tar.gz"
    files:
      - README.md
      - LICENSE

dockers:
  - id: kani-amd64
    image_templates:
      - "joshuasing/kani:{{ .Version }}-amd64"
      - "ghcr.io/hyperadev/kani:{{ .Version }}-amd64"
    goarch: amd64
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.authors="Hypera Development"
      - --label=org.opencontainers.image.url={{ .GitURL }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.vendor="Hypera Development"
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description="Traefik ForwardAuth server for Cloudflare Access"
      - --label=org.label-schema.build-date={{ .Date }}
      - --label=org.label-schema.name={{ .ProjectName }}
      - --label=org.label-schema.description="Traefik ForwardAuth server for Cloudflare Access"
      - --label=org.label-schema.url={{ .GitURL }}
      - --label=org.label-schema.vcs-url={{ .GitURL }}
      - --label=org.label-schema.vcs-ref={{ .FullCommit }}
      - --label=org.label-schema.vendor="Hypera Development"
      - --label=org.label-schema.version={{ .Version }}
      - --label=org.label-schema.schema-version="1.0"
    dockerfile: goreleaser.Dockerfile
  - id: kani-arm64
    image_templates:
      - "joshuasing/kani:{{ .Version }}-arm64"
      - "ghcr.io/hyperadev/kani:{{ .Version }}-arm64"
    goarch: arm64
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.authors="Hypera Development"
      - --label=org.opencontainers.image.url={{ .GitURL }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.vendor="Hypera Development"
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description="Traefik ForwardAuth server for Cloudflare Access"
      - --label=org.label-schema.build-date={{ .Date }}
      - --label=org.label-schema.name={{ .ProjectName }}
      - --label=org.label-schema.description="Traefik ForwardAuth server for Cloudflare Access"
      - --label=org.label-schema.url={{ .GitURL }}
      - --label=org.label-schema.vcs-url={{ .GitURL }}
      - --label=org.label-schema.vcs-ref={{ .FullCommit }}
      - --label=org.label-schema.vendor="Hypera Development"
      - --label=org.label-schema.version={{ .Version }}
      - --label=org.label-schema.schema-version="1.0"
    dockerfile: goreleaser.Dockerfile
  - id: kani-armv7
    image_templates:
      - "joshuasing/kani:{{ .Version }}-armv7"
      - "ghcr.io/hyperadev/kani:{{ .Version }}-armv7"
    goarch: arm
    goarm: "7"
    build_flag_templates:
      - --platform=linux/arm/v7
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.authors="Hypera Development"
      - --label=org.opencontainers.image.url={{ .GitURL }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.vendor="Hypera Development"
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description="Traefik ForwardAuth server for Cloudflare Access"
      - --label=org.label-schema.build-date={{ .Date }}
      - --label=org.label-schema.name={{ .ProjectName }}
      - --label=org.label-schema.description="Traefik ForwardAuth server for Cloudflare Access"
      - --label=org.label-schema.url={{ .GitURL }}
      - --label=org.label-schema.vcs-url={{ .GitURL }}
      - --label=org.label-schema.vcs-ref={{ .FullCommit }}
      - --label=org.label-schema.vendor="Hypera Development"
      - --label=org.label-schema.version={{ .Version }}
      - --label=org.label-schema.schema-version="1.0"
    dockerfile: goreleaser.Dockerfile

docker_manifests:
  - name_template: "joshuasing/kani:latest"
    image_templates:
      - "joshuasing/kani:{{ .Version }}-amd64"
      - "joshuasing/kani:{{ .Version }}-arm64"
      - "joshuasing/kani:{{ .Version }}-armv7"
  - name_template: "joshuasing/kani:{{ .Version }}"
    image_templates:
      - "joshuasing/kani:{{ .Version }}-amd64"
      - "joshuasing/kani:{{ .Version }}-arm64"
      - "joshuasing/kani:{{ .Version }}-armv7"
  - name_template: "joshuasing/kani:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "joshuasing/kani:{{ .Version }}-amd64"
      - "joshuasing/kani:{{ .Version }}-arm64"
      - "joshuasing/kani:{{ .Version }}-armv7"
  - name_template: "ghcr.io/hyperadev/kani:latest"
    image_templates:
      - "ghcr.io/hyperadev/kani:{{ .Version }}-amd64"
      - "ghcr.io/hyperadev/kani:{{ .Version }}-arm64"
      - "ghcr.io/hyperadev/kani:{{ .Version }}-armv7"
  - name_template: "ghcr.io/hyperadev/kani:{{ .Version }}"
    image_templates:
      - "ghcr.io/hyperadev/kani:{{ .Version }}-amd64"
      - "ghcr.io/hyperadev/kani:{{ .Version }}-arm64"
      - "ghcr.io/hyperadev/kani:{{ .Version }}-armv7"
  - name_template: "ghcr.io/hyperadev/kani:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/hyperadev/kani:{{ .Version }}-amd64"
      - "ghcr.io/hyperadev/kani:{{ .Version }}-arm64"
      - "ghcr.io/hyperadev/kani:{{ .Version }}-armv7"

source:
  enabled: true

snapshot:
  name_template: "{{ incpatch .Version }}-dev.{{ .ShortCommit }}"

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test"
      - "^chore"
      - "merge conflict"
      - "^Merge pull request"
      - "^Merge remote-tracking branch"
      - "^Merge branch"
  groups:
    - title: "Dependency updates"
      regexp: "^(chore|fix)\\(deps\\):.*$"
      order: 900
    - title: "Additions"
      regexp: "^feat(\\(.*\\))?:.*$"
      order: 100
    - title: "Fixes"
      regexp: "^fix(\\(.*\\))?:.*$"
      order: 200
    - title: "Documentation"
      regexp: "^docs(\\(.*\\))?:.*$"
      order: 300
    - title: "Other"
      order: 1000

release:
  name_template: "{{.ProjectName}} v{{.Version}}"
  github:
    owner: HyperaDev
    name: kani
  prerelease: auto
  mode: append

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
