project_name: kani

env:
  - AUTHOR=Hypera Development
  - GITHUB_USER=hyperadev
  - DOCKER_HUB_USER=joshuasing
  - DESCRIPTION=Traefik ForwardAuth server for Cloudflare Access

builds:
  - binary: "{{ .ProjectName }}"
    main: "./cmd/{{ .ProjectName }}/"
    env:
      - CGO_ENABLED=0
      - GOGC=off
    ldflags:
      - "-s -w"
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"

archives:
  - id: "{{ .ProjectName }}"
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: "tar.gz"
    files:
      - README.md
      - LICENSE

dockers:
  - id: "{{ .ProjectName }}-amd64"
    goos: linux
    goarch: amd64
    image_templates:
      - "{{ .Env.DOCKER_HUB_USER }}/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Version }}-amd64"
    dockerfile: .goreleaser.Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.authors={{ .Env.AUTHOR }}
      - --label=org.opencontainers.image.url={{ .GitURL }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.vendor={{ .Env.AUTHOR }}
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .Env.DESCRIPTION }}
      - --label=org.label-schema.build-date={{ .Date }}
      - --label=org.label-schema.name={{ .ProjectName }}
      - --label=org.label-schema.description={{ .Env.DESCRIPTION }}
      - --label=org.label-schema.url={{ .GitURL }}
      - --label=org.label-schema.vcs-url={{ .GitURL }}
      - --label=org.label-schema.vcs-ref={{ .FullCommit }}
      - --label=org.label-schema.vendor={{ .Env.AUTHOR }}
      - --label=org.label-schema.version={{ .Version }}
      - --label=org.label-schema.schema-version=1.0
  - id: "{{ .ProjectName }}-arm64v8"
    goos: linux
    goarch: arm64
    image_templates:
      - "{{ .Env.DOCKER_HUB_USER }}/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Version }}-arm64v8"
    dockerfile: .goreleaser.Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.authors={{ .Env.AUTHOR }}
      - --label=org.opencontainers.image.url={{ .GitURL }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.vendor={{ .Env.AUTHOR }}
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .Env.DESCRIPTION }}
      - --label=org.label-schema.build-date={{ .Date }}
      - --label=org.label-schema.name={{ .ProjectName }}
      - --label=org.label-schema.description={{ .Env.DESCRIPTION }}
      - --label=org.label-schema.url={{ .GitURL }}
      - --label=org.label-schema.vcs-url={{ .GitURL }}
      - --label=org.label-schema.vcs-ref={{ .FullCommit }}
      - --label=org.label-schema.vendor={{ .Env.AUTHOR }}
      - --label=org.label-schema.version={{ .Version }}
      - --label=org.label-schema.schema-version=1.0
  - id: "{{ .ProjectName }}-armv7"
    goos: linux
    goarch: arm
    goarm: "7"
    image_templates:
      - "{{ .Env.DOCKER_HUB_USER }}/{{ .ProjectName }}:{{ .Version }}-armv7"
      - "ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Version }}-armv7"
    dockerfile: .goreleaser.Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v7
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.authors={{ .Env.AUTHOR }}
      - --label=org.opencontainers.image.url={{ .GitURL }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.vendor={{ .Env.AUTHOR }}
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .Env.DESCRIPTION }}
      - --label=org.label-schema.build-date={{ .Date }}
      - --label=org.label-schema.name={{ .ProjectName }}
      - --label=org.label-schema.description={{ .Env.DESCRIPTION }}
      - --label=org.label-schema.url={{ .GitURL }}
      - --label=org.label-schema.vcs-url={{ .GitURL }}
      - --label=org.label-schema.vcs-ref={{ .FullCommit }}
      - --label=org.label-schema.vendor={{ .Env.AUTHOR }}
      - --label=org.label-schema.version={{ .Version }}
      - --label=org.label-schema.schema-version=1.0

docker_manifests:
  - name_template: "{{ .Env.DOCKER_HUB_USER }}/{{ .ProjectName }}:latest"
    image_templates:
      - "{{ .Env.DOCKER_HUB_USER }}/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "{{ .Env.DOCKER_HUB_USER }}/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "{{ .Env.DOCKER_HUB_USER }}/{{ .ProjectName }}:{{ .Version }}-armv7"
  - name_template: "{{ .Env.DOCKER_HUB_USER }}/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "{{ .Env.DOCKER_HUB_USER }}/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "{{ .Env.DOCKER_HUB_USER }}/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "{{ .Env.DOCKER_HUB_USER }}/{{ .ProjectName }}:{{ .Version }}-armv7"
  - name_template: "{{ .Env.DOCKER_HUB_USER }}/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "{{ .Env.DOCKER_HUB_USER }}/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "{{ .Env.DOCKER_HUB_USER }}/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "{{ .Env.DOCKER_HUB_USER }}/{{ .ProjectName }}:{{ .Version }}-armv7"
  - name_template: "ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Version }}-armv7"
  - name_template: "ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Version }}-armv7"
  - name_template: "ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}:{{ .Version }}-armv7"

source:
  enabled: true
  name_template: "{{ .ProjectName }}_v{{ .Version }}_sources"

snapshot:
  name_template: "{{ incpatch .Version }}-{{ .ShortCommit }}"

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test"
      - "^chore"
      - "merge conflict"
      - "^Merge pull request"
      - "^Merge remote-tracking branch"
      - "^Merge branch"
  groups:
    - title: "Dependency updates"
      regexp: "^.*(chore|fix)\\(deps\\)*:+.*$"
      order: 300
    - title: "Additions"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: 'Documentation'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: "Other"
      order: 1000

release:
  name_template: "{{ .ProjectName }} v{{ .Version }}"
  github:
    owner: "{{ .Env.GITHUB_USER }}"
    name: "{{ .ProjectName }}"
  prerelease: auto
  mode: append
  footer: |
    **Full Changelog**: https://github.com/{{ .Env.GITHUB_USER }}/{{ .ProjectName }}/compare/{{ .PreviousTag }}...{{ .Tag }}

milestones:
  - repo: # Templating isn't supported here
      owner: "HyperaDev"
      name: "kani"
    close: true

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
