name: Bug Report
description: Create a bug report to help us improve.
labels: [ "status: triage", "type: bug: unconfirmed" ]
body:
  - type: checkboxes
    attributes:
      label: Welcome!
      description: |
        We do not provide support via GitHub issues.
        For questions or general help, please use the [Hypera Discord Server](https://discord.hypera.dev/)

        Please confirm the following.
      options:
        - label: I have checked for similar issues on [GitHub](https://github.com/HyperaDev/kani/issues).
          required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: Please provide a clear and concise description of what the bug is.
      placeholder: When I ..., ... happens.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
      placeholder: Kani should have ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction steps
      description: Provide steps to reproduce this bug
      placeholder: "Please explain how to reproduce this bug"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Please provide information about your operating environment here.
        Make sure to include your operating system name and version, the platform(s) the bug occurs on and the version of the platform(s).
      value: |
        Operating System: <!-- e.g. Ubuntu 22.04 -->
        Architecture: <!-- e.g. AMD64 -->

        Kani version: <!-- e.g. 1.2.0, 'latest' will not be accepted -->
        Docker version: <!-- Run `docker -v` (or N/A if you are not using Docker) -->
        Kubernetes version: <!-- Run `kubectl version` (or N/A if you are not using K8s) -->
      render: Markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Please provide any additional information that may improve the chance of us being able to reproduce and fix this bug.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false