name: Feature Request
description: Suggest an idea for Kani.
labels: [ "status: triage", "type: enhancement" ]
body:
  - type: checkboxes
    attributes:
      label: Welcome!
      description: |
        We do not provide support via GitHub issues.
        For questions or general help, please use the [Hypera Discord Server](https://discord.hypera.dev/)

        Please confirm the following.
      options:
        - label: I have checked for similar issues on [GitHub](https://github.com/HyperaDev/kani/issues).
          required: true
  - type: textarea
    attributes:
      label: Problem
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested solution
      description: Please provide a clear and concise description of what you suggest a solution to this problem would be.
      placeholder: It would be helpful if Kani could ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Please provide any additional information about this feature request.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false