# GitHub Actions workflow to publish project to DockerHub
name: "Docker"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        type: string

jobs:
  stable:
    name: "Deploy stable"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v2

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2

      - name: "Login to DockerHub"
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Build and push"
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: |
            joshuasing/kani:latest
            joshuasing/kani:${{ inputs.version }}
            ghcr.io/HyperaDev/kani:latest
            ghcr.io/HyperaDev/kani:${{ inputs.version }}
