apiVersion: apps/v1
kind: Deployment
metadata:
  name: kani
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kani
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kani
    spec:
      containers:
        - name: kani
          image: joshuasing/kani:latest
          imagePullPolicy: IfNotPresent

          # Environment variables
          env:
            - name: CLOUDFLARE_DOMAIN
              value: "https://<team>.cloudflareaccess.com"

          # Ports
          ports:
            - name: kani-http
              containerPort: 3000

          # Probes
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
          resources:
            limits:
              memory: "32Mi"
              cpu: "1"