apiVersion: v1
kind: Service
metadata:
  name: kani
  namespace: default
  labels:
    app.kubernetes.io/name: kani
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: kani-http
  selector:
    app.kubernetes.io/name: kani